version: 2

jobs:
  build:
    docker:
      - image: bbeanatkitware/cdash-host:latest
      - image: mysql/mysql-server:5.5
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: 'cdash4simpletest'
          MYSQL_ROOT_HOST: '%'
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: 'cdash4simpletest'
          POSTGRES_PASSWORD: ""
    working_directory: /home/kitware/cdash
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Upgrade Chrome
          command: |
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get -y install google-chrome-stable
      - run: sudo ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.conf
      - run: sudo rmdir /var/www/html && sudo ln -s /home/kitware/cdash/public /var/www/html
      - run: chmod a+rwx app/CDash/backup app/CDash/log app/CDash/public/rss app/CDash/public/upload
      - run: sudo composer self-update --no-interaction
      - run: cd app/CDash && composer install --no-interaction --no-progress --prefer-dist
      - run: cd app/CDash && npm install
      - run: composer install --no-interaction --no-progress --prefer-dist
      - run: cp app/CDash/tests/circle/protractor.config.json app/CDash/node_modules/protractor/config.json
      - run: app/CDash/node_modules/.bin/webdriver-manager update
      - run:
          background: true
          command: app/CDash/node_modules/.bin/webdriver-manager start
      - run: cp .env.circleci.mysql .env
      - run: sudo /etc/init.d/apache2 restart
      - run: mkdir _build
      - run: cd _build && cmake -DCDASH_TESTING_RENAME_LOGS=true -DCDASH_DB_HOST=127.0.0.1 -DCDASH_DIR_NAME="" -DCDASH_DB_LOGIN=root -DBUILDNAME="${CIRCLE_BRANCH}_${CIRCLE_BUILD_NUM}_MySQL" -DSITE="CircleCI-2.0" ../app/CDash
      - run: sudo chown -R kitware:www-data /home/kitware/cdash && sudo chmod -R 770 /home/kitware/cdash
      - run: cd _build && ctest --extra-verbose --no-compress-output --track Experimental --test-action Test --test-action Submit .
#      - run: rm -rf _build && mkdir _build
#      - run: cd _build && cmake -DCDASH_TESTING_RENAME_LOGS=true -DCDASH_DB_TYPE=pgsql -DCDASH_DIR_NAME="" -DCDASH_DB_LOGIN=postgres -DBUILDNAME="${CIRCLE_BRANCH}_${CIRCLE_BUILD_NUM}_PostgreSQL" -DSITE="CircleCI-2.0" ../app/CDash
#      - run: cd _build && ctest --extra-verbose --no-compress-output --track Continuous --test-action Test --test-action Submit .
